fix: accept full height of container
solid-design-system/solid pull request #1036
Opened 2024-05-03 12:34 UTC by yoezlem

## Description:
Changed the logic regarding #719 to accept full height inside a container 

## Definition of Reviewable:
- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated
- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

2024-05-03 15:05 UTC, mariohamann requested changes

2024-05-03 15:05 UTC, mariohamann commented on packages/components/src/components/textarea/textarea.ts
> +      <div part="form-control" class="flex flex-col w-full text-left">
Does this fully preserve the ability to set rows? When does it use rows, when the height? Some documentation or even better a story would be very helpful here.

2024-05-08 15:02 UTC, mariohamann commented
I removed myself – feel free to re-add if needed.

2024-05-14 19:29 UTC, mariohamann commented on packages/components/src/components/textarea/textarea.ts
> +      <div part="form-control" class="flex flex-col w-full text-left">
@yoezlem Anything you need here? :)

2024-05-15 06:39 UTC, Vahid1919 approved these changes

2024-05-15 17:17 UTC, azraefendic approved these changes

2024-06-13 06:17 UTC, closed without merging