Docs: sd-flag docs [skip chromatic]
solid-design-system/solid pull request #1278
Opened 2024-08-13 08:15 UTC by auroraVasconcelos

## Description:
## Definition of Reviewable:

- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated
- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

2024-08-19 05:34 UTC, mariohamann commented on packages/components/src/styles/flag/flag.stories.ts
> +  render: () => html` <div class="sd-flag">Default</div> `
Make dynamic again.

2024-08-19 05:34 UTC, mariohamann commented on packages/components/src/styles/flag/flag.stories.ts
> + * - white: use the class `sd-flag--white`
See chip.

2024-08-19 05:34 UTC, mariohamann commented on packages/components/src/templates/flag.stories.ts
> + */
See chip: https://github.com/solid-design-system/solid/pull/1277#discussion_r1721230766

2024-08-19 11:05 UTC, yoezlem commented
Seems like we had an error with the deployment. 
@mariohamann @auroraVasconcelos could you guys check that please?

2024-08-19 16:47 UTC, MartaPintoTeixeira reviewed
The 1st preview of the component should be named "Flag" as it is in FIGMA.
We use the same logic in Button Storybook

2024-08-20 11:37 UTC, yoezlem requested changes
Seems like, we have two "Related Templates" in Figma:
<img width="488" alt="image" src="https://github.com/user-attachments/assets/f52d72fc-2335-4970-8681-65b1a9583422">

2024-08-20 13:59 UTC, auroraVasconcelos commented
> Seems like, we have two "Related Templates" in Figma: <img alt="image" width="488" src="https://private-user-images.githubusercontent.com/98025014/359460174-f52d72fc-2335-4970-8681-65b1a9583422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjI1NzMsIm5iZiI6MTcyNDE2MjI3MywicGF0aCI6Ii85ODAyNTAxNC8zNTk0NjAxNzQtZjUyZDcyZmMtMjMzNS00OTcwLTg2ODEtNjViMWE5NTgzNDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEzNTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YWQ0ZTYzYzc0ODA1MzJhYjg0N2JhNmE2MDIyNTRhNzQwOGJhYTIxY2JmNDZlNjMwNGEzMDNjZTZmNTQ2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1H3EvpHC3YFMqWenrKfOqHSZxIZ34wMqRekUdXVG0Vg">

2024-08-20 14:01 UTC, auroraVasconcelos commented
> Seems like, we have two "Related Templates" in Figma: <img alt="image" width="488" src="https://private-user-images.githubusercontent.com/98025014/359460174-f52d72fc-2335-4970-8681-65b1a9583422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjI1NzMsIm5iZiI6MTcyNDE2MjI3MywicGF0aCI6Ii85ODAyNTAxNC8zNTk0NjAxNzQtZjUyZDcyZmMtMjMzNS00OTcwLTg2ODEtNjViMWE5NTgzNDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEzNTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YWQ0ZTYzYzc0ODA1MzJhYjg0N2JhNmE2MDIyNTRhNzQwOGJhYTIxY2JmNDZlNjMwNGEzMDNjZTZmNTQ2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1H3EvpHC3YFMqWenrKfOqHSZxIZ34wMqRekUdXVG0Vg">

@yoezlem in this case the teaser template hasn't been implemented yet there for we would have a link for something that doesn't exist (yet). I can either add it here or when the template is added. What would be the prefereble approach?

2024-08-20 14:05 UTC, MartaPintoTeixeira commented
Regarding Related templates:
I have added "Teaser" to the Related templates since in this component template we have "Teaser with Chip and Flag" and I though it made sense to announce it in the Chip and Flag components. Let me know what you think @coraliefeil.

2024-08-21 12:30 UTC, coraliefeil commented
Let’s sort out the whole template thing at the end. 
Approved.

2024-08-22 12:58 UTC, mariohamann approved these changes

2024-08-22 12:59 UTC, mariohamann approved these changes

2024-08-22 13:28 UTC, merged