fix: 🤔 update experimental status
solid-design-system/solid pull request #1396
Opened 2024-09-17 13:43 UTC by Vahid1919

## Description:

Closes #1209.
 
I did not change the "since" version number as we did not make any changes in the component. Please let me know if I should change it to our current version.

## Definition of Reviewable:

- [x] Documentation is created/updated
- [x] relevant tickets are linked

2024-09-17 13:48 UTC, smfonseca approved these changes

2024-09-17 13:52 UTC, yoezlem approved these changes

2024-09-17 16:46 UTC, karlbaumhauer requested changes
I don't want to be picky but if we use the status, the version should be correct... ;-)

2024-09-17 16:46 UTC, karlbaumhauer commented on packages/components/src/components/link/link.ts
>   * @since 1.2
looking at our changelog, its stable since our init of the components => Verison 1.0.0

2024-09-17 16:46 UTC, karlbaumhauer commented on packages/components/src/styles/hidden-links/hidden-links.declaration.ts
> +  status: 'stable',
looking at our changelog it has been added in version 3.15.0

2024-09-17 16:46 UTC, karlbaumhauer commented on packages/components/src/styles/hidden-links/hidden-links.declaration.ts
>    since: '3.12.0',
```suggestion
  since: '3.15.0',
```

2024-09-17 16:46 UTC, karlbaumhauer commented on packages/components/src/styles/list/list.declaration.ts
>    since: '1.33.1',
looking at our changelog it has been added in version 1.39.0

2024-09-19 09:10 UTC, karlbaumhauer approved these changes

2024-09-20 13:15 UTC, merged