fix: licensing and placeholder images [skip chromatic]
solid-design-system/solid pull request #1547
Opened 2024-10-11 14:45 UTC by karlbaumhauer

## Description:
- removes all un-approvd images from placeholder package BREAKING CHANGE
- adds information on logos used in our components package

## Definition of Reviewable:
- [x] Documentation is created/updated
- [x] Stories (features, a11y) are created/updated

2024-10-11 16:29 UTC, smfonseca approved these changes

2024-10-11 18:18 UTC, mariohamann requested changes
Fortunately this is not a Breaking Change!

Maybe the message didn't reach you, but placeholders were published 3 months ago the last time. As the images were added in a "docs" merge, no release was triggered so far.

Therefore we can savely make a "chore" commit, as this will neither impact current versions of components nor placeholders.

One note in addition: Are you sure, that none of the images is part of a screenshot test? At least for the final deployment, please remove the [skip chromatic] flag, to ensure fresh tests.

2024-10-15 12:45 UTC, karlbaumhauer commented
> Fortunately this is not a Breaking Change!
> 
> Maybe the message didn't reach you, but placeholders were published 3 months ago the last time. As the images were added in a "docs" merge, no release was triggered so far.
> 
> Therefore we can savely make a "chore" commit, as this will neither impact current versions of components nor placeholders.
> 
> One note in addition: Are you sure, that none of the images are part of a screenshot test? At least for the final deployment, please remove the [skip chromatic] flag, to ensure fresh tests.

@mariohamann / @smfonseca I replaced the sds-logo with the ui-brand-mark and added this image to storybook assets instead of the placeholder package.

I also removed the [skip chromatic] to make sure its not f❌ng on any template.

@MartaPintoTeixeira / @coraliefeil pls have a look and you might need to change the Figma template as well (from what I saw there).

2024-10-15 15:44 UTC, MartaPintoTeixeira approved these changes

2024-10-16 09:38 UTC, mariohamann approved these changes

2024-10-16 09:42 UTC, merged