feat: add 'md' size to sd-radio, sd-checkbox and sd-checkbox-group
solid-design-system/solid pull request #1549
Opened 2024-10-14 14:13 UTC by Vahid1919

## Description:

Closes #1326 

## Definition of Reviewable:

- [x] Documentation is created/updated
- [x] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated

- [x] Stories (features, a11y) are created/updated
- [x] relevant tickets are linked

2024-10-15 09:32 UTC, karlbaumhauer requested changes
just added some suggestions in order to make the sm === md thing more clear.

2024-10-15 09:32 UTC, karlbaumhauer commented on packages/components/src/components/checkbox-group/checkbox-group.stories.ts
>   * Use the `size` attribute to change the size:
```suggestion
 * Use the `size` attribute to change the size (`md` equals `sm` but added for consistency reason on input elements):
```

2024-10-15 09:32 UTC, karlbaumhauer commented on packages/components/src/components/checkbox/checkbox.stories.ts
>   * Use the `size` attribute to change the size of the input checkbox:
```suggestion
 * Use the `size` attribute to change the size of the input checkbox (`md` equals `sm` but added for consistency reason on input elements):
```

2024-10-15 09:32 UTC, karlbaumhauer commented on packages/components/src/components/radio-button/radio-button.stories.ts
l50 should be changed as well in order to match the rest of the suggestions "(`md` equals `sm` but added for consistency reason on input elements)"

2024-10-15 13:41 UTC, Vahid1919 commented
> I would also like to change the title as this is actually a feature of the components itself...?!?

Thanks for the feedback. According to figma and what I already understood, md should actually be equal to lg. So I will mention that in the docs. 

In regards to the title. I assumed it is a fix since it is a feature that was missing (hence broken radio-button-groups) and not a brand new feature that we are adding. What do you think @karlbaumhauer

2024-10-15 14:59 UTC, karlbaumhauer commented
> > I would also like to change the title as this is actually a feature of the components itself...?!?
> 
> Thanks for the feedback. According to figma and what I already understood, md should actually be equal to lg. So I will mention that in the docs.
oh sh**t... mixed up the lines, sorry. I updated my suggestions.

> In regards to the title. I assumed it is a fix since it is a feature that was missing (hence broken radio-button-groups) and not a brand new feature that we are adding. What do you think @karlbaumhauer
You are right for the radio-group. This would be a fix.
But... As you are changing the other components as well and adding a new value to the components properties (without fixing a bug), it would be a feature. Even though it actually does not do anything feature-like (only adding it for consistency reasons... ;-)).

In theory, you would need to split the changes in one fix (radio-group) and another feature to checkbox and checkbox-group.

2024-10-16 10:33 UTC, yoezlem approved these changes

2024-10-16 16:04 UTC, smfonseca approved these changes

2024-10-17 14:25 UTC, Vahid1919 commented
@karlbaumhauer I updated the docs to include the documentation. I also changed the title to feat since that better explains all the changes

2024-10-17 15:41 UTC, karlbaumhauer approved these changes

2024-10-18 07:10 UTC, merged