feat: sd-map-marker a11y
solid-design-system/solid pull request #1577
Opened 2024-10-22 16:26 UTC by smfonseca

## Description:

## Definition of Reviewable:

- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated

- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

2024-10-24 09:56 UTC, auroraVasconcelos submitted a review, later dismissed

2024-10-24 12:03 UTC, karlbaumhauer requested changes
pls also add the description and link the ticket.

2024-10-24 12:03 UTC, karlbaumhauer commented on packages/components/src/components/map-marker/map-marker.ts
for some reason I cannot tab through the whole story in Safari at all... is this only on my side?

2024-10-25 11:07 UTC, smfonseca commented on packages/components/src/components/audio/audio.test.ts
I included it here because the tests were failing and I wanted to quickly address it. But makes sense to instead do it in a separate branch.

2024-10-29 15:48 UTC, smfonseca commented on packages/components/src/components/map-marker/map-marker.stories.ts
> +      <sd-map-marker label="example"></sd-map-marker>
I opted to remove the label because we can instead use the `sr-only` class to provide an accessible name.

2024-10-29 15:50 UTC, smfonseca commented on packages/components/src/components/map-marker/map-marker.ts
If it's not interactive, it's focusable, therefore you cannot tab through it

2024-10-29 15:51 UTC, smfonseca commented on packages/components/src/components/map-marker/map-marker.stories.ts
> +      <sd-map-marker label="example"></sd-map-marker>
I've updated the accessible names, but I'm still not fully happy with it. Do you have some suggestions?

2024-10-29 16:51 UTC, karlbaumhauer submitted a review, later dismissed

2024-10-30 14:49 UTC, MartaPintoTeixeira commented
#1588 looking good.

2024-10-31 06:52 UTC, mariohamann approved these changes

2024-10-31 09:46 UTC, MartaPintoTeixeira commented
For the template instead of:
"Map Maker with Images"
Lets have:
"Map Maker with Image"

2024-10-31 10:59 UTC, smfonseca commented
> For the template instead of: "Map Maker with Images" Lets have: "Map Maker with Image"

Updated

2024-10-31 11:15 UTC, smfonseca commented
@MartaPintoTeixeira we added an accessiblity hint. Please include it in figma also

2024-10-31 12:01 UTC, MartaPintoTeixeira commented
For the cluster on the 2nd line can you make it in line with the components next to it? @smfonseca

2024-10-31 15:28 UTC, MartaPintoTeixeira approved these changes

2024-10-31 18:00 UTC, mariohamann approved these changes

2024-10-31 18:01 UTC, merged