feat: sd-combobox & sd-combobox a11y
solid-design-system/solid pull request #1633
Opened 2024-11-11 15:19 UTC by DanielHargesheimer

## Description:
This PR closes [1387](https://github.com/solid-design-system/solid/issues/1387) and [1495](https://github.com/solid-design-system/solid/issues/1495)

## Definition of Reviewable:

- [x] Documentation is created/updated
- [x] E2E tests (features, a11y, bug fixes) are created/updated

- [x] Stories (features, a11y) are created/updated
- [x] relevant tickets are linked

2024-11-12 08:04 UTC, karlbaumhauer commented
@DanielHargesheimer pls resolve conflicts as it seems like the deployment has been blocked with it. Review not possible without feature branch deployment.

2024-11-12 08:42 UTC, DanielHargesheimer commented
I removed the CloseWatcher, which synergy uses in the select, too. As we don't use it in the sd-select, I'm not really sure why we need it and it don't seem to work with our setup, I decided to remove it.

2024-11-15 08:29 UTC, mariohamann commented on packages/docs/src/stories/components/combobox.stories.ts
> + * Use to group `s visually.
I have the feeling here's something off.

2024-11-15 08:29 UTC, mariohamann commented on packages/docs/src/stories/components/combobox.stories.ts
> +          ${createColorOptionHtml('Black')} ${createColorOptionHtml('Blue')} ${createColorOptionHtml('Brown')}
Not sure if I really like this abstraction here. ^^

2024-11-15 08:29 UTC, mariohamann commented on packages/docs/src/stories/components/combobox.stories.ts
> +      <sd-combobox size="lg" label="Label" placement="bottom" clearable value="option-1">
I have the feeling that the color of (x) is wrong. @coraliefeil

2024-11-15 08:29 UTC, mariohamann commented on packages/docs/src/stories/components/combobox.stories.ts
> + */
The component should stay open when selecting an element:

See e. g. https://solid-design-system.fe.union-investment.de/docs/?path=/docs/components-sd-select--docs#multiple and https://vaadin.com/docs/latest//components/multi-select-combo-box

2024-11-15 08:29 UTC, mariohamann commented on packages/docs/src/stories/components/combobox.stories.ts
> +export const NoOptions = {
What is this?

2024-11-15 08:37 UTC, mariohamann commented on packages/components/src/components/combobox/combobox.ts
It would be great if you could add a disclaimer [here](https://solid-design-system.github.io/solid/feat_sd-combobox/?path=/docs/templates-autocomplete--docs) that the support of `autocomplete.js` is deprecated and will be removed completely in one of the next two major versions of Solid.

2024-11-15 08:44 UTC, DanielHargesheimer commented on packages/docs/src/stories/components/combobox.stories.ts
> +export const NoOptions = {
Ah, I forgot to delete it, sorry.

2024-11-19 14:11 UTC, DanielHargesheimer commented
@coraliefeil @mariohamann
Please have a look again.
I have revised the behavior of the tags according to Coralie's suggestion. Now, you can delete the last tag by backspace.
I have added the "tag-ellipsis" boolean attribute. ([story](https://solid-design-system.github.io/solid/feat_sd-combobox/?path=/docs/components-sd-combobox--docs#tag%20ellipsis))
Here I am not sure. Would it perhaps be better to maintain the character count through the attribute and specify 15 as the default? I'm open for name suggestions :)

2024-11-20 07:55 UTC, mariohamann commented
Love to see that, and keyboard handling feels great for a first iteration. Thanks!!!

Regarding max char: Let's change this to a CSS property, being set on the host. Let's call it just `--tag-max-width` and set it to 15ch per default. This enables it so that people can override easily with some specific values by setting it on the element itself, e. g. `<sd-combobox style="--tax-max-width: 40px">` or whatever.

2024-11-20 07:56 UTC, mariohamann commented
And from my feeling, we can optin to always useTags. As the "tags-area" should be a part, people can easily then just set it to display none if they don't want to use it, like e. g. in the download search.

2024-11-20 12:07 UTC, coraliefeil commented
Review done. Pls address comments.

Thanks a lot @DanielHargesheimer - great job! Pls reassign for another review.

2024-11-21 13:49 UTC, coraliefeil commented
Yes great. design-wise we’ll follow your definitions. Thanks

2024-11-21 15:03 UTC, smfonseca reviewed
Currently when using multiple, when I select an option, it will be added in the same order that it is displayed in the dropdown. My expectation is that the last selected option shows up last place. I know we have the same behaviour in the sd-select, but feels a bit odd to me. What do you think @coraliefeil @mariohamann?

https://github.com/user-attachments/assets/86e12f26-4c18-4c89-9b1c-307f09fcd3c7

2024-11-21 19:28 UTC, coraliefeil commented
> Currently when using multiple, when I select an option, it will be added in the same order that it is displayed in the dropdown. My expectation is that the last selected option shows up in last place. I know we have the same behaviour in the sd-select, but feels a bit odd to me. What do you think @coraliefeil @mariohamann?
> 
>  combobox.mov

Sounds very reasonable @smfonseca. I like your suggestion a lot actually. So let’s change the order of the tags shown in the field so that they appear in the order of their selection and not in the order of the option list. 
What are everyone else's thoughts?

2024-11-22 09:56 UTC, DanielHargesheimer commented on packages/components/src/components/combobox/combobox.ts
> +              ${hasClearIcon
I don't know exactly what you mean. The sd-select code seems to be the same.
`@focus=${() => this.focus()}` (select.ts: line 946)

2024-11-22 10:34 UTC, smfonseca commented on packages/components/src/components/combobox/combobox.ts
> +              ${hasClearIcon
Sorry, should have been more precise. I meant not making the clearable button focusable with keyboard, and a better example for this is the sd-input.

2024-11-26 08:30 UTC, DanielHargesheimer commented
@coraliefeil, @smfonseca, @mariohamann
Please have a look again. If this solution is good, I'll adapt sd-select.

2024-11-26 11:40 UTC, coraliefeil commented
THX. Pls reassign for next review.

2024-11-26 14:56 UTC, DanielHargesheimer commented
@coraliefeil 
Now, it should behave like the Morningstar Combo Box.

2024-11-26 20:02 UTC, coraliefeil commented
Great! Pls apply shadow token to the flyout ... then we are done. Thanks a lot!

2024-11-27 08:36 UTC, DanielHargesheimer commented
The sd-select has a broken shadow, too. There is something wrong with the .shadow class. I'll have a look.

2024-11-27 13:38 UTC, coraliefeil commented
Pls rename sd-optgroup to sd-option-group. THX.

2024-11-28 16:44 UTC, coraliefeil commented
See chromatic comments

2024-11-29 11:47 UTC, coraliefeil commented
Pls move these to the template section and add a template for "Combobox" there.

Add headline "Related Templates" and below link to "Combobox" at the top of the docs page underneath comp description.

Simple Suggests -> show data like in [figma](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/W0LTcrsplIFyHJonYNyqsG/Solid-DS-%E2%80%93-Component-Library?node-id=29958-16983&node-type=frame&t=4YclZamMZWxUYbvi-11)

Highlight Query -> show data like in [figma](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/W0LTcrsplIFyHJonYNyqsG/Solid-DS-%E2%80%93-Component-Library?node-id=29958-16983&node-type=frame&t=4YclZamMZWxUYbvi-11)

Grouping Query -> show data like in [figma](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/W0LTcrsplIFyHJonYNyqsG/Solid-DS-%E2%80%93-Component-Library?node-id=29958-16983&node-type=frame&t=4YclZamMZWxUYbvi-11)

--

On docs page:

For "Multiple" it would be good to show data with ... like in [Figma](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/W0LTcrsplIFyHJonYNyqsG/Solid-DS-%E2%80%93-Component-Library?node-id=29661-7024&node-type=frame&t=4YclZamMZWxUYbvi-11)

For "Multiple Options Visible" pls show data like in [figma](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/W0LTcrsplIFyHJonYNyqsG/Solid-DS-%E2%80%93-Component-Library?node-id=29661-7024&node-type=frame&t=4YclZamMZWxUYbvi-11)

For "Icon" -> move section below "Clearable"
Change text to -> Use the ”left” and “right” slots to add system icons.
Show search icon in left either left or right icon slot with the chevron icon (don’t show 2 icons on the right hand side)
Not showing the label here is only fine when showing search-icon.
Add -> Accessibility hint: Label can be omitted for search input fields if a button (e.g., aria-label="Search") with a search icon is present. 
See [figma](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/W0LTcrsplIFyHJonYNyqsG/Solid-DS-%E2%80%93-Component-Library?node-id=29661-7024&node-type=frame&t=4YclZamMZWxUYbvi-11)

2024-11-29 12:53 UTC, coraliefeil commented
Add description to sd-optgroup and display underneath headline
-> Used to group selectable items within various form controls such as select.

2024-12-02 08:30 UTC, mariohamann commented on packages/components/src/components/combobox/combobox.ts
We updated our release process last week. If you need support for the following, please reach out! :)

---

Please add an appropriate changeset by running `pnpm changeset` from root.

This is how a changeset message could look like:

```
Improved a11y for sd-tab-group.

  - Improve keyboard navigation.
  - Added labels to icons for the navigation buttons.
  - Added focus styles for tab panels.
```

2024-12-03 13:10 UTC, coraliefeil commented
Use the disabled attribute in the <syn-optgroup> to disable the Section and prevent it from being selected.

-> Use the disabled attribute in the <sd-optgroup> to disable the section and prevent it from being selected.

2024-12-03 13:18 UTC, coraliefeil commented
On [this page](https://64469bd84c5ea1ce2dd5d016-bpibvleunt.chromatic.com/?path=/docs/components-sd-optgroup--docs) add:

Related Components:

[sd-combobox](https://64469bd84c5ea1ce2dd5d016-bpibvleunt.chromatic.com/?path=/docs/components-sd-combobox--docs)
[sd-select](https://64469bd84c5ea1ce2dd5d016-bpibvleunt.chromatic.com/iframe.html?path=/docs/components-sd-select--docs)

Related templates:

[Autocomplete](https://64469bd84c5ea1ce2dd5d016-bpibvleunt.chromatic.com/iframe.html?path=/docs/templates-autocomplete--docs)

2024-12-03 13:19 UTC, coraliefeil commented
On [this page](https://64469bd84c5ea1ce2dd5d016-bpibvleunt.chromatic.com/?path=/docs/components-sd-select--docs)

Add sd-optgroup link to related components

2024-12-03 13:20 UTC, coraliefeil commented
On [this page](https://64469bd84c5ea1ce2dd5d016-bpibvleunt.chromatic.com/?path=/docs/components-sd-combobox--docs)

Add 

Related components:

[sd-optgroup] (https://64469bd84c5ea1ce2dd5d016-bpibvleunt.chromatic.com/?path=/docs/components-sd-optgroup--docs)

[sd-option](https://64469bd84c5ea1ce2dd5d016-bpibvleunt.chromatic.com/iframe.html?path=/docs/components-sd-option--docs)

2024-12-03 13:22 UTC, coraliefeil commented
For all placeholder text -> color has to be text.neutral-700

2024-12-03 13:27 UTC, coraliefeil commented
Pls mirror what we have in [figma](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=9809-63694&node-type=frame&t=aYw1zl70Yy2NY5DB-11) to show up on [Storybook](https://64469bd84c5ea1ce2dd5d016-bpibvleunt.chromatic.com/?path=/docs/components-sd-combobox--docs#icons)

2024-12-03 13:29 UTC, coraliefeil commented
Pls reassign when comments have been addressed. THX a lot!

2024-12-03 15:01 UTC, smfonseca commented
@DanielHargesheimer just a quick remark regarding changesets: there's no need to add two different changesets if there is no version bump between them. You can add one and then edit it as many times as needed with the necessary information.
It's also good to include in it more detailed information about the relevant changes introduced by the PR.

2024-12-04 09:20 UTC, coraliefeil commented on packages/components/src/components/combobox/combobox.ts
> +        this.clearCombobox();
[Here](https://designsystem.morningstar.com/components/combo-box/?version=5.1.0&tab=variations&fwk=Vue%202#multiselect) the ESC closes the flyout. 
Would do it like that. If you all agree.

2024-12-04 09:25 UTC, DanielHargesheimer commented on packages/components/src/components/combobox/combobox.ts
> +        this.clearCombobox();
Yes, it closes the flyout and deletes the search term. But the combobox value and the tags are still there.

2024-12-04 09:32 UTC, coraliefeil commented on packages/components/src/components/combobox/combobox.ts
> +        this.clearCombobox();
Is it somehow instable? It cleared the search term on the first try and kept the tags. On second try it kept the search term and the tags. On third try hitting ESC multiple times it deleted search term and tags.

..?

2024-12-04 09:33 UTC, coraliefeil commented
<img width="1050" alt="Bildschirmfoto 2024-12-04 um 10 28 06" src="https://github.com/user-attachments/assets/319baa8c-44aa-4d12-b460-b3dedc6962ec">

Could we add sth like this for cases were no suggestion / option can be found?

2024-12-04 09:35 UTC, DanielHargesheimer commented on packages/components/src/components/combobox/combobox.ts
> +        this.clearCombobox();
Ah, sorry, right now our combobox clears all :) But it should work like the Morningstar combobox. I'll do that.

2024-12-04 09:47 UTC, DanielHargesheimer commented
> <img alt="Bildschirmfoto 2024-12-04 um 10 28 06" width="1050" src="https://private-user-images.githubusercontent.com/41894356/392312371-319baa8c-44aa-4d12-b460-b3dedc6962ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDU1ODQsIm5iZiI6MTczMzMwNTI4NCwicGF0aCI6Ii80MTg5NDM1Ni8zOTIzMTIzNzEtMzE5YmFhOGMtNDRhYS00ZDEyLWI0NjAtYjNkZWRjNjk2MmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA5NDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOGYyYThmNWEyZWE1NDBjZjgxOWI0ZTEwMTRmZGNmMWJmMzA0OTg0ZjgyYTYzMDViZjkzNGM3YzFiN2I3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8yS26ZNgfCNmhGK60roUQzgPZexsReB4OuvxulO0kWI">
> Could we add sth like this for cases were no suggestion / option can be found?
> 
> If we do so ... should we document this in a section? How is it documented on dev side?

I can do a screenshot like [simple-suggests](https://64469bd84c5ea1ce2dd5d016-bpibvleunt.chromatic.com/?path=/story/components-sd-combobox-screenshots-sd-combobox--simple-suggests)

2024-12-06 14:13 UTC, coraliefeil commented
Approved. Thank you so much!

2024-12-09 10:42 UTC, smfonseca commented on packages/components/src/translations/de.ts
> +  tagsSelected: 'Optionen ausgewählt',
Please sort alphabetically. Also in the `de` and `en` files.

2024-12-09 11:57 UTC, paulovareiro29 requested changes
Hi @DanielHargesheimer, thank you so much for all the work, it's looking great!

Regarding `sd-select`:
Currently, when using keyboard navigation in the `sd-select` with tags, it is impossible to delete option tags unless you go specifically to the selected options on the popover and unselect them. I would have two recommendations here:
- (Ideally) Implementing backspace to delete options. When using keyboard navigation, options can be focused. If an option is focused and `backspace` is pressed, delete the tag. 
- When an option is focused and `space` is pressed to open the popover, the previously focused option should be the one that is focused on the popover. This way keyboard navigation + screenreader users would have a much better experience.

Once again, thanks a lot for your work!

2024-12-10 08:31 UTC, DanielHargesheimer commented
Hi @paulovareiro29,
these are good points, I'll have a look on it. The backspace solution is used in the combobox in a nearly similar way, so it should take not much time.

2024-12-10 09:32 UTC, DanielHargesheimer commented
> * (Ideally) Implementing backspace to delete options. When using keyboard navigation, options can be focused. If an option is focused and `backspace` is pressed, delete the tag.

@paulovareiro29, @coraliefeil
Why should we do it differently here than with the combobox? First focus and then delete and not delete immediately?

2024-12-10 10:04 UTC, DanielHargesheimer commented
> * When an option is focused and `space` is pressed to open the popover, the previously focused option should be the one that is focused on the popover. This way keyboard navigation + screenreader users would have a much better experience.

@paulovareiro29
I'm not sure what you mean. I tested it again and it works exactly as you described.

2024-12-11 00:34 UTC, paulovareiro29 commented
Hi @DanielHargesheimer , looks great, thanks for implementing the suggestions so quickly!
I have just another quick improvement, which I think makes sense:
- In the sd-combobox, when a tag is focused and backspace is pressed, the tag gets deleted and the combobox (input) gets focused, great!
- In the sd-select, after the same process, when the tag gets deleted, the focus is lost. I believe in this case, another option tag should be selected. (It could always be the option that comes after, or if non existent, the option that was before)

Let me know what you think and if you have any questions, feel free to reach out!

2024-12-11 00:43 UTC, paulovareiro29 commented
> When an option is focused and space is pressed to open the popover, the previously focused option should be the one that is focused on the popover. This way keyboard navigation + screenreader users would have a much better experience.

As agreed with Daniel, I have created a new issue to tackle this: #1722

2024-12-11 09:14 UTC, paulovareiro29 approved these changes
Looking great, thanks!

2024-12-11 09:29 UTC, smfonseca approved these changes

2024-12-11 09:33 UTC, merged