feat!: implement new sd-flipcard
solid-design-system/solid pull request #1703
Opened 2024-12-04 10:33 UTC by Vahid1919

## Description:

!BREAKING CHANGE

## Definition of Reviewable:

- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated

- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

2024-12-04 16:22 UTC, mariohamann commented
As this is a breaking change, it could be, that we move over your changes into https://github.com/solid-design-system/solid/pull/1689 to the end of the week. Please wait with merging.

2024-12-04 16:22 UTC, mariohamann commented on packages/components/src/components/flipcard/flipcard.test.ts
As this is a breaking change, it could be, that we move over your changes into https://github.com/solid-design-system/solid/pull/1689 to the end of the week. Please wait with merging.

2024-12-05 08:15 UTC, smfonseca commented
@Vahid1919 after flipping, I would suggest we move the focus to the back button. What do you think?

2024-12-05 14:37 UTC, Vahid1919 commented
> @Vahid1919 after flipping, I would suggest we move the focus to the back button. What do you think?

@smfonseca When focusing directly on the button would not read the slot content since that appears before the button. By focusing on the slot, we could directly read the content and the flip button is 1 tab away.

2024-12-05 15:20 UTC, MartaPintoTeixeira commented
In docs can we have "placement section" 1st and after that "aspect ratios" section?

2024-12-05 15:21 UTC, MartaPintoTeixeira commented
In figma docs we still have the "activation" section. Should I delete it? Since you don't have it in dev and is code-only?

2024-12-05 15:22 UTC, MartaPintoTeixeira commented
In the "flip direction" section can we change it to:
"Use the ”flip-direction” attribute to determine the direction of the flipcard when flip button is clicked:"
We think it makes sense to reinforce the importance of the button.

2024-12-05 15:25 UTC, MartaPintoTeixeira commented
The flipcards are not flipping when i click the buttons. Can you make it work please?

2024-12-05 15:25 UTC, MartaPintoTeixeira commented
Also flipcards template has been updated in figma:
https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=2314-197533&node-type=canvas&t=cvX6GKBzBRtzE2b9-0
Can we implement it here? Or we need a new ticket?

2024-12-05 16:41 UTC, paulovareiro29 requested changes
Hi Vahid, here are a few thoughts from my end:
- Flip button is not working when clicked using the cursor
- The `default` story has slotted media but has the default primary background, therefore making the media not visible. Does it make sense to have the slotted media in the Default story?
- When using the keyboard navigation and not flipping the card, I can still navigate to the `content / flip button` from the back side. As a visual and keyboard user, it doesn't feel natural that the navigation goes to the back side, if I didn't press to flip it.

2024-12-06 09:44 UTC, Vahid1919 commented
> In figma docs we still have the "activation" section. Should I delete it? Since you don't have it in dev and is code-only?

Yes, it can be removed. @MartaPintoTeixeira

2024-12-06 10:05 UTC, Vahid1919 commented
> * The `default` story has slotted media but has the default primary background, therefore making the media not visible. Does it make sense to have the slotted media in the Default story?
> * When using the keyboard navigation and not flipping the card, I can still navigate to the `content / flip button` from the back side. As a visual and keyboard user, it doesn't feel natural that the navigation goes to the back side, if I didn't press to flip it.

@paulovareiro29 

Regarding `default` story - I agree that including an image with the primary variant does not make sense as it is not visible, but the media slot is included so that the gradient slots have access to the image when you switch variants using the controls. 

About accessing the back side, it will be taken care of here [#1477](https://github.com/solid-design-system/solid/issues/1477)

2024-12-06 10:11 UTC, MartaPintoTeixeira commented
@Vahid1919  will you be able to check the templates in this ticket?
If not, please open a ticket to replicate figma templates in storybook.

The other requested changes from my side have passed the 2nd review.

2024-12-06 10:16 UTC, MartaPintoTeixeira approved these changes, later dismissed
@Vahid1919 will you be able to check the templates in this ticket? If yes, re-assign me once ready.

If not, please open a ticket to replicate flipcard figma templates in storybook and consider it approved from my side.

2024-12-06 10:37 UTC, Vahid1919 commented
> @Vahid1919 will you be able to check the templates in this ticket? If yes, re-assign me once ready.
> 
> If not, please open a ticket to replicate flipcard figma templates in storybook and consider it approved from my side.

I would prefer to keep those in a different ticket :) @MartaPintoTeixeira

2024-12-09 10:59 UTC, smfonseca approved these changes

2024-12-09 10:59 UTC, smfonseca commented on .changeset/strange-items-clap.md
> +- update tests and templates.
```suggestion
!Breaking Change

Implement new sd-flipcard concept:

- Remove 'activation' feature.
- Include a dedicated button to trigger the flip (clicking the card and hovering will no longer trigger a flip).
- Remove 'empty' variant and set 'primary' as the default variant.
- Add 'placement' feature to set the position of the default slots for both the front and back cards.
- Simplify variants to remove any positioning logic (eg: gradient-light-top -> gradient-light)
- Update tests and templates.
```

2024-12-09 11:01 UTC, smfonseca commented on .changeset/strange-items-clap.md
> +- update tests and templates.
@Vahid1919 I've approved the PR but please do not merge yet as per [Mario's request](https://github.com/solid-design-system/solid/pull/1703#discussion_r1869887585).

2024-12-09 11:09 UTC, MartaPintoTeixeira commented
I have created this ticket for the template update:
feat[dev]: ✨ Update flipcard template [#1714](https://github.com/solid-design-system/solid/issues/1714)

2024-12-11 09:37 UTC, mariohamann commented
Merged into #1689.

2024-12-11 09:37 UTC, closed without merging