fix: make sd-tooltip more accessible
solid-design-system/solid pull request #1712
Opened 2024-12-06 12:56 UTC by Vahid1919

## Description:

## Definition of Reviewable:

- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated

- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

2024-12-12 16:14 UTC, Vahid1919 commented
@MartaPintoTeixeira I added a new story for the tooltip docs at the end. Please take a look and let me know if I should make any changes before we align it with Figma :) 
 https://solid-design-system.github.io/solid/fix_sd-tooltip-a11y/iframe.html?viewMode=docs&id=components-sd-tooltip--docs#custom%20buttons

2024-12-17 12:19 UTC, MartaPintoTeixeira commented
Custom Buttons section:

Copy suggestion: Note: Currently, this method is not recommended due to issues with passing ID references to the shadow DOM, which can make the tooltip text inaccessible to screen readers. We are actively working on a solution to resolve this limitation.

2025-01-14 15:43 UTC, MartaPintoTeixeira commented
Something is wrong in the 1st tooltip sample
<img width="496" alt="Screenshot 2025-01-14 at 15 42 37" src="https://github.com/user-attachments/assets/34f2a77d-2b1c-4b92-bd0b-52867964a900" />

2025-01-14 15:45 UTC, MartaPintoTeixeira commented
Samples inside the Placement section have a weird behaviour in responsive screens (this is also happening in the current storybook link) should we open a ticket for this?

2025-01-21 14:46 UTC, MartaPintoTeixeira commented
As discussed via call:
- in the template instead of "Home page" write "Home" as in figma
- to prevent the accessibility of 1st and last sd-navigation item lets add a padding top of 4 before the 1st group of sd-navigation items and a padding of 4 after the sd-navigation items of the footer section
- left and right paddings to be dicussed in the daily

2025-01-28 14:39 UTC, MartaPintoTeixeira commented
Component is still broken. Assign me again once fixed.
<img width="1057" alt="Screenshot 2025-01-28 at 14 39 10" src="https://github.com/user-attachments/assets/12e03078-cc57-421d-ac3b-8b0d9dbb0edb" />

2025-01-28 14:40 UTC, MartaPintoTeixeira requested changes
Component is still broken. Assign me again once fixed.

2025-01-28 15:46 UTC, smfonseca commented
> Component is still broken. Assign me again once fixed.

Fix is in [#1798](https://github.com/solid-design-system/solid/pull/1798)

2025-01-30 15:04 UTC, MartaPintoTeixeira requested changes
In the tmplt: Select with Tooltip
can you align it as Top Start Positioning? Because now is not perfectly centered.

2025-01-30 15:20 UTC, smfonseca reviewed
Please double check click after hover as discussed on call

2025-02-06 11:37 UTC, smfonseca commented on packages/components/src/components/tooltip/tooltip.test.ts
> +  it('should close tooltip when clicking trigger if it was opened by focus', async () => {
Since the trigger is only `focus`, clicking the button shouldn't hide the tooltip, this is only happening because on L256 you're using `blur()`. I think it would be easier to check the `open` attribute when focusing on the button and then when removing focus.

2025-02-06 11:37 UTC, smfonseca commented on packages/components/src/components/tooltip/tooltip.test.ts
> +    // tooltip is visible after clicking the button
```suggestion
    // tooltip is visible after focusing the button
```

2025-02-06 11:37 UTC, smfonseca commented on packages/components/src/components/tooltip/tooltip.test.ts
> +    expect(document.activeElement).to.not.equal(el);
I think this assertion is not needed

2025-02-11 12:07 UTC, mariohamann commented on packages/components/src/components/tooltip/tooltip.test.ts
> +    expect(document.activeElement).to.not.equal(el);
Wasn't there a bug that triggered this behaviour?

2025-02-12 16:34 UTC, auroraVasconcelos commented on packages/components/src/components/tooltip/tooltip.test.ts
> +    expect(document.activeElement).to.not.equal(el);
@smfonseca @mariohamann,
There was one specific situation we would have this bug:
![image (75)](https://github.com/user-attachments/assets/5c411226-a50f-4e40-b34b-bb52cc375dc2)

Therefore I added this situation to the tests in order to prevent this bug to happen again

2025-02-13 13:07 UTC, paulovareiro29 requested changes
LGTM
Just some commented code that needs to be removed if not necessary

2025-02-13 13:07 UTC, paulovareiro29 commented on packages/docs/src/stories/components/tooltip.stories.ts
> +  // parameters: { ...parameters, docs: { story: { inline: false, height: '800px' } } },
remove dead code if not necessary

2025-02-13 14:33 UTC, MartaPintoTeixeira submitted a review, later dismissed

2025-02-13 16:08 UTC, auroraVasconcelos commented on packages/docs/src/stories/components/tooltip.stories.ts
> +  // parameters: { ...parameters, docs: { story: { inline: false, height: '800px' } } },
Updated

2025-02-13 16:29 UTC, paulovareiro29 approved these changes

2025-02-13 22:19 UTC, merged