fix: improve sd-expandable a11y
solid-design-system/solid pull request #1724
Opened 2024-12-11 12:18 UTC by paulovareiro29

## Description:
Closes #1476 

This PR addresses:
- Reorder of sd-expandable dom order. (button first so it is targetable by keyboard first)
- Improvement of the sd-expandable template labels
- Added accessibility hints to sd-expandable

## Definition of Reviewable:

- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated

- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

2024-12-12 11:48 UTC, MartaPintoTeixeira commented
Accessibility hints added in storybook were now added to figma.

2024-12-12 14:44 UTC, paulovareiro29 commented
Hi @MartaPintoTeixeira @coraliefeil ,
I have adjusted the spacings between the content and the button to look like figma. In figma there is a spacing of 16px. Previously, on implementation, there was none.

2024-12-20 02:16 UTC, Vahid1919 commented on packages/docs/src/stories/components/expandable.stories.ts
> + * **Accessibility Hints:**
```suggestion
 * **Accessibility Information:**
```
Keeping it consistent with Accessibility Information in #1670

2024-12-20 10:49 UTC, smfonseca commented on .changeset/violet-bulldogs-draw.md
> +- Added accessibility hints to sd-expandable
```suggestion
- Reorder elements in the DOM (button first so it is targetable by keyboard on first tab)
- Improved template labels
- Added accessibility hints
```

2024-12-20 10:49 UTC, smfonseca commented on packages/docs/src/stories/components/expandable.stories.ts
> + * - Generic summaries like "show more" should be avoided.
I think we should update our stories to reflect this recommendation, right now we are still showing "show more"

2024-12-20 15:54 UTC, smfonseca approved these changes

2025-01-09 09:08 UTC, mariohamann approved these changes

2025-01-13 15:53 UTC, MartaPintoTeixeira commented
Since we have an accessibility hint saying "Generic summaries like "show more" should be avoided." 
Should we consider renaming the "Show more" button that opens the expandable to "Expand to read more content"?

2025-01-13 16:21 UTC, paulovareiro29 commented
FYI: Talked directly with Marta and we agreed on changing the default translations to:
"Show Less" -> "Collapse to show less"
"Show More" -> "Expand to show more"

This would be the default translations and still not recommended to be used on a production environment, but still it is better.

This default translations would only be used on the default component on the docs.

2025-01-13 16:45 UTC, MartaPintoTeixeira commented
As spoken please remove underlines bellow the labels as in the main component.

2025-01-13 17:03 UTC, MartaPintoTeixeira commented
"Accessibility Hint" instead of "Accessibility information" for consistency please

2025-01-14 08:23 UTC, mariohamann commented
> Since we have an accessibility hint saying "Generic summaries like "show more" should be avoided."
> Should we consider renaming the "Show more" button that opens the expandable to "Expand to read more content"?

This is in no way less generic, but just more text. The guideline aims more to avoid repeating, non-descriptive links, see e. g. https://www.visionaustralia.org/business-consulting/digital-access/blog/how-to-make-read-more-links-accessible

Expanding this to more text makes this even worse.

2025-01-14 08:29 UTC, coraliefeil commented
I’ll ask Damaris. I’m having a sync with her today.

2025-01-14 09:17 UTC, MartaPintoTeixeira commented
> > Since we have an accessibility hint saying "Generic summaries like "show more" should be avoided."
> > Should we consider renaming the "Show more" button that opens the expandable to "Expand to read more content"?
> 
> This is in no way less generic, but just more text. The guideline aims more to avoid repeating, non-descriptive links, see e. g. https://www.visionaustralia.org/business-consulting/digital-access/blog/how-to-make-read-more-links-accessible
> 
> Expanding this to more text makes this even worse. I'm not sure, if we can do anything about this inside our components.
> 
> @MartaPintoTeixeira @paulovareiro29

Okay in that case let's reverse this changes @paulovareiro29

2025-01-14 12:00 UTC, MartaPintoTeixeira commented
@mariohamann 

While reviewing the sd-expandable I have noticed that in the current version in storybook the label is underlined. But in figma we dont use underline for expandable.
While speaking with Vasconcelos, Aurora (EXT/Partner) (Guest) we checked that the element is an sd-interactive and as so it should not have underline as well.
I would like to check if we should keep the underline or remove it please.

2025-01-14 12:00 UTC, MartaPintoTeixeira requested changes
Waiting for a question to be answered to approve PR

2025-01-14 15:03 UTC, MartaPintoTeixeira commented
fix: 🤔 sd-expandable label underline to be removed
[#1778](https://github.com/solid-design-system/solid/issues/1778)

bug ticket created

2025-01-14 15:04 UTC, MartaPintoTeixeira submitted a review, later dismissed
Approved from design side. 
Bug found: fix: 🤔 sd-expandable label underline to be removed
[#1778](https://github.com/solid-design-system/solid/issues/1778)

2025-01-14 17:07 UTC, MartaPintoTeixeira submitted a review, later dismissed

2025-01-15 16:21 UTC, smfonseca approved these changes

2025-01-15 16:24 UTC, merged