feat: ✨ Add sd-badge (#232)
solid-design-system/solid pull request #326
Opened 2023-08-10 07:37 UTC by MarcMatthiae

2023-08-10 11:29 UTC, karlbaumhauer requested changes

2023-08-10 11:29 UTC, karlbaumhauer commented on packages/components/src/components/badge/badge.stories.ts
> +      url: 'https://www.figma.com/file/fPGhgNZv98U4H69Gu2tlWi/Button?type=design&node-id=13-18&t=jDLqFEdY7ZlOJurc-4'
still the Button URL

2023-08-10 11:29 UTC, karlbaumhauer commented on packages/components/src/components/badge/badge.stories.ts
> + * <b>Why did we add a slot for the overflow-indicator?</b>
seems like a dev-comment...?!? pls remove

2023-08-10 11:29 UTC, karlbaumhauer commented on packages/components/src/components/badge/badge.ts
> + * @since 1.0
shouldnt this be the future version when merged to `main`?

2023-08-10 13:07 UTC, karlbaumhauer approved these changes

2023-08-10 13:23 UTC, mariohamann commented
![CleanShot 2023-08-10 at 15 20 53@2x](https://github.com/solid-design-system/solid/assets/26542182/173558dc-a0f3-4539-b793-4d37960c8ad2)

The Overflow indicator is not vertically centered. And it needs a padding to the left.

![CleanShot 2023-08-10 at 15 21 52@2x](https://github.com/solid-design-system/solid/assets/26542182/b680a0eb-b3db-44b6-8f6d-2f6b66f65e38)

1. This prop shouldn't exist, it should be handled via slot.
2. You shouldn't set the default in the story, otherwise it's ignored if you want to do something.
3. Add doumentation, that you should add the plus here to see it.

2023-08-10 13:24 UTC, mariohamann commented
<img width="1552" alt="CleanShot 2023-08-10 at 15 23 58@2x" src="https://github.com/solid-design-system/solid/assets/26542182/4f054587-2ed6-4644-9eb8-1b77f0ef3eea">

Please show this with md and sm buttons, reflecting the size of the badge as well.

2023-08-10 13:25 UTC, mariohamann commented
<img width="1034" alt="CleanShot 2023-08-10 at 15 25 02@2x" src="https://github.com/solid-design-system/solid/assets/26542182/e7c9f5ed-4456-4812-9fc1-b4526c1ba48f">

Why doesn't the overflow indicator show up? Please only use the slot, no prop for it.

2023-08-10 13:29 UTC, mariohamann commented
<img width="525" alt="CleanShot 2023-08-10 at 15 28 32@2x" src="https://github.com/solid-design-system/solid/assets/26542182/4c6e0247-6d13-4f5a-a260-825efc66f44b">

I'm not sure if this behaviour is correct. :)

I think it should be right-aligned, but maybe the designers have another opinion on that?

2023-08-10 13:31 UTC, mariohamann commented on packages/components/src/components/badge/badge.stories.ts
> +/* eslint-disable @typescript-eslint/no-non-null-assertion */
Do not disable eslint.

2023-08-10 13:31 UTC, mariohamann commented on packages/components/src/components/badge/badge.test.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-explicit-any, @typescript-eslint/no-shadow
Do not disable eslint.

2023-08-10 13:32 UTC, mariohamann commented on packages/components/src/components/badge/badge.ts
> +  @property({ type: Boolean, reflect: true }) overflowing = false;
This shouldn't exist.

2023-08-10 13:43 UTC, mariohamann commented
@MarcMatthiae Always add designers to the PR, as they have to approve, too.

@solid-design-system/design

You can still access Storybook here:
![CleanShot 2023-08-10 at 15 42 51@2x](https://github.com/solid-design-system/solid/assets/26542182/cef58b75-2dd4-48ec-a758-6ee355c13315)

2023-08-10 18:30 UTC, coraliefeil commented
> <img alt="CleanShot 2023-08-10 at 15 28 32@2x" width="525" src="https://user-images.githubusercontent.com/26542182/259756989-4c6e0247-6d13-4f5a-a260-825efc66f44b.png">
> I'm not sure if this behaviour is correct. :)
> 
> I think it should be right-aligned, but maybe the designers have another opinion on that?

Yes, thank you for pointing that out @mariohamann. 1 digit is centered in the element corner. More digits - width increases to the left / badge is right-aligned.

2023-08-10 18:36 UTC, coraliefeil commented
> @MarcMatthiae Always add designers to the PR, as they have to approve, too.
> 
> @solid-design-system/design
> 
> You can still access Storybook here: ![CleanShot 2023-08-10 at 15 42 51@2x](https://user-images.githubusercontent.com/26542182/259761153-cef58b75-2dd4-48ec-a758-6ee355c13315.png)

Storybook publish link is missing ... is there another link?

2023-08-10 18:55 UTC, mariohamann commented
> > @MarcMatthiae Always add designers to the PR, as they have to approve, too.
> > @solid-design-system/design
> > You can still access Storybook here: ![CleanShot 2023-08-10 at 15 42 51@2x](https://user-images.githubusercontent.com/26542182/259761153-cef58b75-2dd4-48ec-a758-6ee355c13315.png)
> 
> Storybook publish link is missing ... is there another link?

You have click on "Details", sorry.

2023-08-11 13:56 UTC, MarcMatthiae commented
> > <img alt="CleanShot 2023-08-10 at 15 28 32@2x" width="525" src="https://user-images.githubusercontent.com/26542182/259756989-4c6e0247-6d13-4f5a-a260-825efc66f44b.png">
> > I'm not sure if this behaviour is correct. :)
> > I think it should be right-aligned, but maybe the designers have another opinion on that?
> 
> Yes, thank you for pointing that out @mariohamann. 1 digit is centered in the element corner. More digits - width increases to the left / badge is right-aligned.

> > <img alt="CleanShot 2023-08-10 at 15 28 32@2x" width="525" src="https://user-images.githubusercontent.com/26542182/259756989-4c6e0247-6d13-4f5a-a260-825efc66f44b.png">
> > I'm not sure if this behaviour is correct. :)
> > I think it should be right-aligned, but maybe the designers have another opinion on that?
> 
> Yes, thank you for pointing that out @mariohamann. 1 digit is centered in the element corner. More digits - width increases to the left / badge is right-aligned.

@mariohamann @coraliefeil Are you sure? Shoelace does it like I did.

2023-08-11 13:57 UTC, MarcMatthiae commented
> > > <img alt="CleanShot 2023-08-10 at 15 28 32@2x" width="525" src="https://user-images.githubusercontent.com/26542182/259756989-4c6e0247-6d13-4f5a-a260-825efc66f44b.png">
> > > I'm not sure if this behaviour is correct. :)
> > > I think it should be right-aligned, but maybe the designers have another opinion on that?
> > 
> > 
> > Yes, thank you for pointing that out @mariohamann. 1 digit is centered in the element corner. More digits - width increases to the left / badge is right-aligned.
> 
> > > <img alt="CleanShot 2023-08-10 at 15 28 32@2x" width="525" src="https://user-images.githubusercontent.com/26542182/259756989-4c6e0247-6d13-4f5a-a260-825efc66f44b.png">
> > > I'm not sure if this behaviour is correct. :)
> > > I think it should be right-aligned, but maybe the designers have another opinion on that?
> > 
> > 
> > Yes, thank you for pointing that out @mariohamann. 1 digit is centered in the element corner. More digits - width increases to the left / badge is right-aligned.
> 
> @mariohamann @coraliefeil Are you sure? Shoelace does it like I did.

![image](https://github.com/solid-design-system/solid/assets/3873797/1182d22b-9117-4438-a6dc-5045298c23f1)

2023-08-11 14:21 UTC, mariohamann commented
> > @mariohamann @coraliefeil Are you sure? Shoelace does it like I did.

Well Shoelace is our base, but regarding design we change stuff. Do you see problems in implementing it?

2023-08-11 14:27 UTC, mariohamann commented
![CleanShot 2023-08-11 at 16 26 36@2x](https://github.com/solid-design-system/solid/assets/26542182/7c0510fe-e199-4ff9-a5ba-1db572c899b7)

The numbers are not vertically centered here.

2023-08-11 14:31 UTC, mariohamann commented on packages/components/src/components/badge/badge.test.ts
> +    });
As we have visual testing (somethign Shoelace doesn't have!) I would say you can omit all tests that check for specific TailwindClasses.

In that case you're more testing if cx works, but that's not part of our job.

2023-08-11 14:32 UTC, mariohamann commented on packages/components/src/components/badge/badge.ts
> +        top: calc(((-1em / 1.5) + 1ex) / 2);
Please provide some explenation why you came up with this calculation.

2023-08-14 14:24 UTC, MarcMatthiae commented
> ![CleanShot 2023-08-11 at 16 26 36@2x](https://user-images.githubusercontent.com/26542182/260033995-7c0510fe-e199-4ff9-a5ba-1db572c899b7.png)
> 
> The numbers are not vertically centered here.

@mariohamann @coraliefeil Can we change the font size for the medium badge to 11? With the current font size of 10 the text is not vertically centered inside the badge due to the font.

2023-08-14 14:25 UTC, MarcMatthiae commented
> > > > <img alt="CleanShot 2023-08-10 at 15 28 32@2x" width="525" src="https://user-images.githubusercontent.com/26542182/259756989-4c6e0247-6d13-4f5a-a260-825efc66f44b.png">
> > > > I'm not sure if this behaviour is correct. :)
> > > > I think it should be right-aligned, but maybe the designers have another opinion on that?
> > > 
> > > 
> > > Yes, thank you for pointing that out @mariohamann. 1 digit is centered in the element corner. More digits - width increases to the left / badge is right-aligned.
> > 
> > 
> > > > <img alt="CleanShot 2023-08-10 at 15 28 32@2x" width="525" src="https://user-images.githubusercontent.com/26542182/259756989-4c6e0247-6d13-4f5a-a260-825efc66f44b.png">
> > > > I'm not sure if this behaviour is correct. :)
> > > > I think it should be right-aligned, but maybe the designers have another opinion on that?
> > > 
> > > 
> > > Yes, thank you for pointing that out @mariohamann. 1 digit is centered in the element corner. More digits - width increases to the left / badge is right-aligned.
> > 
> > 
> > @mariohamann @coraliefeil Are you sure? Shoelace does it like I did.
> 
> ![image](https://user-images.githubusercontent.com/3873797/260026666-1182d22b-9117-4438-a6dc-5045298c23f1.png)

Actually, this needs to be done in the button component, right?

2023-08-14 14:33 UTC, mariohamann commented
> > > > > <img alt="CleanShot 2023-08-10 at 15 28 32@2x" width="525" src="https://user-images.githubusercontent.com/26542182/259756989-4c6e0247-6d13-4f5a-a260-825efc66f44b.png">
> > > > > I'm not sure if this behaviour is correct. :)
> > > > > I think it should be right-aligned, but maybe the designers have another opinion on that?
> > > > 
> > > > 
> > > > Yes, thank you for pointing that out @mariohamann. 1 digit is centered in the element corner. More digits - width increases to the left / badge is right-aligned.
> > > 
> > > 
> > > > > <img alt="CleanShot 2023-08-10 at 15 28 32@2x" width="525" src="https://user-images.githubusercontent.com/26542182/259756989-4c6e0247-6d13-4f5a-a260-825efc66f44b.png">
> > > > > I'm not sure if this behaviour is correct. :)
> > > > > I think it should be right-aligned, but maybe the designers have another opinion on that?
> > > > 
> > > > 
> > > > Yes, thank you for pointing that out @mariohamann. 1 digit is centered in the element corner. More digits - width increases to the left / badge is right-aligned.
> > > 
> > > 
> > > @mariohamann @coraliefeil Are you sure? Shoelace does it like I did.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/3873797/260026666-1182d22b-9117-4438-a6dc-5045298c23f1.png)
> 
> Actually, this needs to be done in the button component, right?

Yes. If you want, you can leave it out completely at this point and we wait until design provides the sample, too.

2023-08-15 11:24 UTC, MarcMatthiae commented
Pipeline failing because of color accessibility problems when using token bg-success. Waiting for token update.

2023-08-16 10:02 UTC, mariohamann commented on packages/components/src/components/badge/badge.stories.ts
> + */
Could please write this as markdown instead of HTML?

2023-08-17 08:16 UTC, mariohamann approved these changes

2023-08-17 13:50 UTC, mariohamann commented
@solid-design-system/design Did you already give your approval?

2023-08-17 18:28 UTC, coraliefeil commented
> @solid-design-system/design Did you already give your approval?

Review done. Just 2 tiny things. Then we are good to go. Thank you all <3

2023-08-18 08:02 UTC, mariohamann commented on packages/components/src/components/badge/badge.ts
> +        <span part="content" class=${cx(this.size === 'sm' && `hidden`)}>
```suggestion
        <span part="content" class=${cx(this.size === 'sm' && 'hidden')}>
```

2023-08-18 08:04 UTC, mariohamann commented on packages/components/src/components/badge/badge.ts
> +            error: !this.inverted ? `text-white bg-error border-white` : `text-white bg-error border-primary`
```suggestion
          'inline-flex items-center justify-center gap-x-[1px] text-center leading-none whitespace-nowrap border rounded-full select-none cursor-[inherit]',
          {
            /* variants */
            default: !this.inverted ? 'text-white bg-primary-500 border-white' : 'text-primary bg-white border-primary',
            success: !this.inverted ? 'text-white bg-success border-white' : 'text-white bg-success border-primary',
            error: !this.inverted ? 'text-white bg-error border-white' : 'text-white bg-error border-primary'
```

2023-08-18 10:07 UTC, merged