docs: optimize contributing guidelines
solid-design-system/solid pull request #618
Opened 2023-11-27 13:04 UTC by mariohamann

## Description:
*PR notes: Please describe the changes in this PR.*

Optimized Contribution Guidelines, merges them with Release Guide and Shows them in Storybook.

## Definition of Reviewable:
*PR notes: Irrelevant elements should be removed.*
- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated
- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked
- [ ] PR is assigned to project board

2023-11-28 14:05 UTC, karlbaumhauer commented on CONTRIBUTING.md
> +To perform a documentation-only deployment, make a commit on main with `docs: ` prefix. The pipelines will automatically recognize (by checking the commit message) that only documentation has been up
to prevent multiple updates in the future if we change the process.

2023-11-29 09:29 UTC, abudd1094 commented on CONTRIBUTING.md
> +  - Provide stories for props, slots etc. in Storybook. [Explore components and interact with them](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/).
It's a little confusing, I agree, could just remove the link.  I think Mario's idea was to lead the users to "explore" components in the Storybook.

2023-11-29 09:32 UTC, abudd1094 approved these changes
Good improvements here.  We can refine further if needed.  I'll give it additional thought before I exit the process based on my own experience.  Thanks for updating!

2023-11-29 09:37 UTC, mariohamann commented on CONTRIBUTING.md
> +  - Provide stories for props, slots etc. in Storybook. [Explore components and interact with them](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/).
This was a copy paste thing from the old docs. I'll remove it. 😆

2023-11-29 09:39 UTC, mariohamann commented on CONTRIBUTING.md
> +  - Provide stories for props, slots etc. in Storybook. [Explore components and interact with them](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/).
```suggestion
  - Provide stories for props, slots etc. in Storybook
```

2023-11-29 09:50 UTC, mariohamann commented on CONTRIBUTING.md
> +> Note: The pipeline checks the last commit and sets one of 3 possible deployment type. This step ensures that a new version is deployed only when there is a new release and only the docs are deploye
I improved it. Could you have a look again? If it doesn't fit, feel free to rewrite. (It was just copy paste. :D)

2023-11-29 12:24 UTC, karlbaumhauer requested changes

2023-11-29 12:24 UTC, karlbaumhauer commented on CONTRIBUTING.md
> +  - Provide stories for props, slots etc. in Storybook
would it make sense (as the point has been mentioned in #622) to explain a bit more detailed what we are using the stories for?

2023-11-29 12:24 UTC, karlbaumhauer commented on CONTRIBUTING.md
> +> - `docs`: This type is set when the last commit message starts with 'docs:' and deploys only the Storybook to the CDN
```suggestion
> - `docs`: This type is set when the last commit message starts with `docs:` and deploys only the Storybook to the CDN
```

2023-11-29 12:24 UTC, karlbaumhauer commented on CONTRIBUTING.md
> +> - `code`: This type is set when the last commit message starts with `chore(release/components)` it deploys to the CDN
```suggestion
> - `code`: This type is set when the last commit message starts with `chore(release/components):` (coming from a semantic-release version bump) and it deploys everything to the CDN
```

2023-11-29 12:24 UTC, karlbaumhauer commented on CONTRIBUTING.md
> +> Note: The pipeline checks the last commit and sets one of 3 possible deployment type. This step ensures that a new version is deployed only when there is a new release and only the docs are deploye
added 2 suggestions but rather than this, its fine. thx.

2023-11-29 13:13 UTC, abudd1094 commented
@karlbaumhauer to continue the conversation from Azra's ticket...

To fix the "confusion" we would need an even better CONTRIBUTING.md and more attentive reviews.  Frankly I don't find this structure effective to communicate what I now understand about this project.

We have a combination of technologies (Shoelace, Storybook, Chromatic, etc...) and it is not self-explanatory how they come together.  Perhaps it was clear at the conception among the members of the core team but not to any others who join. 

The most effective set of guidelines would reduce wordiness around explaining concepts and communicate concisely each consideration of the developer.  This includes prioritzing the explanation of technologies and how they are expected to be used.  For the topic of stories, an explicit section in CONTRIBUTING.md:

## Stories
We write stories primarily as visual tests for [Chromatic](https://www.chromatic.com/).  The idea is to create screenshots of every possible visual scenario so we can easily review when there may be breaking changes.  Additionally, we have a limited number of "screenshots" in Chromatic, so it is best to minimize the total amount of stories.  Do this by combining different visual tests with the use of our "Storybook Helpers" axis properties.  (Provide some markup & examples).

This short paragraph would have made it 100% clear to me from day one what the stories are supposed to be about.  Make it easy, section title "Stories", immediately explain the purpose in this context.  

I'll leave the project by December 18th latest, and need to reduce a few days in between based on my current utilization.  I could elaborate on my own ideal guidelines based on my experience here if you think that would be helpful.

2023-11-29 15:24 UTC, karlbaumhauer commented
> @karlbaumhauer to continue the conversation from Azra's ticket...
> 
> To fix the "confusion" we would need an even better CONTRIBUTING.md and more attentive reviews. Frankly I don't find this structure effective to communicate what I now understand about this project.
> 
> We have a combination of technologies (Shoelace, Storybook, Chromatic, etc...) and it is not self-explanatory how they come together. Perhaps it was clear at the conception among the members of the core team but not to outsiders.
> 
> The most effective set of guidelines would reduce wordiness around explaining concepts and communicate concisely each consideration of the developer. This includes prioritzing the explanation of technologies and how they are expected to be used. For the topic of stories, an explicit section in CONTRIBUTING.md:
> 
> ## Stories
> We write stories primarily as visual tests for [Chromatic](https://www.chromatic.com/). The idea is to create screenshots of every possible visual scenario so we can easily review when there may be breaking changes. Additionally, we have a limited number of "screenshots" in Chromatic, so it is best to minimize the total amount of stories. Do this by combining different visual tests with the use of our "Storybook Helpers" axis properties. (Provide some markup & examples).
> 
> This short paragraph would have made it 100% clear to me from day one what the stories are supposed to be about. Make it easy, section title "Stories", immediately explain the purpose in this context.
> 
> Currently we have a mix of language based more around concepts rather than explicit development guidelines: ![image](https://private-user-images.githubusercontent.com/39494579/286605667-0af6d3c1-34a4-4e10-9f26-930852240c97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzE2NTcsIm5iZiI6MTcwMTI3MTM1NywicGF0aCI6Ii8zOTQ5NDU3OS8yODY2MDU2NjctMGFmNmQzYzEtMzRhNC00ZTEwLTlmMjYtOTMwODUyMjQwYzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE1MjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYmNkNzRkN2I5OTkxMGQzZjc2ZWQ1ZTJhNmFkZGE5MzJjYzU1YTVjYzZiYjcwOWVmMjYxYmI5MTM1ZDhkMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.46KRQ5FTgEW4ji7ItmuVVDGk3bUxe6S6bRhpY7JidcI)
> 
> I think Mario did well here elaborating on the existing guidelines, but it needs more for outsiders to gain quick and effective understanding. I'll leave the project by December 18th latest, and need to reduce a few days in between based on my current utilization. I could draft my own ideal guidelines based on my experience here if you think that would be helpful. I would approve this and create a new ticket if so.

thx @abudd1094 for the explanation. My suggestion: As soon as @mariohamann merged this PR, you branch off `main` and push your suggestion. Afterwards, you & me are going through it and in case you can finish it within your time here in this project, its fine otherwise I will take care of it and might just ask you for short feedback afterwards.

2023-11-30 12:37 UTC, yoezlem approved these changes

2023-12-08 11:45 UTC, merged

2023-12-08 11:45 UTC, mariohamann commented
@karlbaumhauer I integrated all suggestions and allowed me to merge. :)