docs: add tokens handling
solid-design-system/solid pull request #697
Opened 2024-01-19 10:55 UTC by van-nguyen-ht

## Description:
Adding tokens handling for maintainers in Figma to README
closes #531 

## Definition of Reviewable:
*PR notes: Irrelevant elements should be removed.*
- [x] Documentation is created/updated
- [x] Migration Guide is created/updated
- [x] relevant tickets are linked
- [ ] PR is assigned to project board

2024-01-22 13:34 UTC, mariohamann requested changes
I don't think that the README as the first entrypoint on GitHub is the right place for that. This feels more like something that should be added to `Contributing.md`. If you add it there, please align with the writing style we have there.

2024-01-22 13:34 UTC, mariohamann commented on README.md
> +Any changes in the token set in Token Studio plugin must be in a new branch.
```suggestion
Any changes in the token set in Token Studio plugin must be in a new branch branched from `main`.
```

2024-01-22 13:34 UTC, mariohamann commented on README.md
> +Note: If the token is related to Figma native style i.e.: color, choose "create styles" so Figma style and token are in sync
```suggestion
> Note: If the token is related to Figma native style i.e.: color, choose "create styles" so Figma style and token are in sync
```

2024-01-22 13:34 UTC, mariohamann commented on README.md
> +After front-end's aproval, check if all tests are passed (quality gate, etc.), then hit Squash and Merge button, write a message (especially if there's any changes in token naming or deprecating note
```suggestion
After front-end's approval and all tests are passed (quality gate, Chromatic tests etc.) hit `Squash and Merge` button, write a message (especially if there's any changes in token naming or deprecating note "BREAKING CHANGE: ..."
```

2024-01-24 09:07 UTC, mariohamann commented
> I don't think that the README as the first entrypoint on GitHub is the right place for that. This feels more like something that should be added to `Contributing.md`. If you add it there, please align with the writing style we have there.

@karlbaumhauer @yoezlem What's your opinion on that? This feels way to specific for a general README.

2024-01-25 10:43 UTC, karlbaumhauer commented
> > I don't think that the README as the first entrypoint on GitHub is the right place for that. This feels more like something that should be added to `Contributing.md`. If you add it there, please align with the writing style we have there.
> 
> @karlbaumhauer @yoezlem What's your opinion on that? This feels way to specific for a general README.

I personally feel like the README as this is very special for the designers and thy can easily access the information once they are on GItHub (which they need to maintain the tokens). I would suggest to go with the README for now and see if we might get more details for designers and then open up a new file/location for this.

2024-01-25 10:43 UTC, karlbaumhauer requested changes

2024-01-25 10:43 UTC, karlbaumhauer commented on README.md
> +### Handling tokens (for maintainers)
```suggestion
### Handling tokens (for Figma maintainers ONLY)
```

2024-01-26 09:11 UTC, karlbaumhauer commented
> > > I don't think that the README as the first entrypoint on GitHub is the right place for that. This feels more like something that should be added to `Contributing.md`. If you add it there, please align with the writing style we have there.
> > 
> > 
> > @karlbaumhauer @yoezlem What's your opinion on that? This feels way to specific for a general README.
> 
> @mariohamann I personally feel like the README as this is very special for the designers and thy can easily access the information once they are on GItHub (which they need to maintain the tokens). I would suggest to go with the README for now and see if we might get more details for designers and then open up a new file/location for this.

agreed in the daily:
it should be part of the `packages/tokens/README.md`
FYI @van-nguyen-ht

2024-01-26 10:13 UTC, karlbaumhauer approved these changes

2024-01-26 11:54 UTC, merged