docs: 📚 show tokens in Storybook [skip chromatic]
solid-design-system/solid pull request #757
Opened 2024-02-14 19:46 UTC by saemik94

## Description:
closes #355 

## Definition of Reviewable:
*PR notes: Irrelevant elements should be removed.*
- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated
- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

2024-02-15 09:32 UTC, yoezlem commented on packages/components/src/docs/General/07-Tokens.mdx
> +            <div class="font-bold whitespace-nowrap ">sd-font-size-{token[0]}</div>
Please remove the whitespace

2024-02-15 09:33 UTC, yoezlem commented on packages/components/src/docs/General/07-Tokens.mdx
> +            <div class="font-bold whitespace-nowrap ">sd-font-size-{token[0]}</div>
https://github.com/solid-design-system/solid/pull/757/files#r1490703574

2024-02-15 09:33 UTC, yoezlem commented on packages/components/src/docs/General/07-Tokens.mdx
> +              <div class="font-bold whitespace-nowrap ">sd-spacing-{token[0]}</div>
https://github.com/solid-design-system/solid/pull/757/files#r1490703574

2024-02-15 09:33 UTC, yoezlem commented on packages/components/src/docs/General/07-Tokens.mdx
> +              <div class="font-bold whitespace-nowrap ">sd-opacity-{token[0]}</div>
https://github.com/solid-design-system/solid/pull/757/files#r1490703574

2024-02-15 09:33 UTC, yoezlem commented on packages/components/src/docs/General/07-Tokens.mdx
> +              <div class="font-bold whitespace-nowrap ">--sd-shadow-{token[0]}</div>
https://github.com/solid-design-system/solid/pull/757/files#r1490703574

2024-02-19 07:04 UTC, saemik94 commented
This PR also includes #728

2024-02-20 12:57 UTC, mariohamann commented on packages/tokens/src/create-theme.cjs
> +  )}, ${getColor('#FF0000')}) / <alpha-value>) /* Exclusively for marking fonds */`;
```suggestion
  const colorMappings = {
  'success': {
    color: '#25880E',
    comment: 'Used for success messages'
  },
  'warning': {
    color: '#BB8D20',
    comment: 'Used for notifications'
  },
  'risk-low': {
    color: '#017DC3',
    comment: 'Exclusively for marking fonds'
  },
  'risk-moderate': {
    color: '#00A593',
    comment: 'Exclusively for marking fonds'
  },
  'risk-increased': {
    color: '#FFF000',
    comment: 'Exclusively for marking fonds'
  },
  'risk-high': {
    color: '#FA9B1E',
    comment: 'Exclusively for marking fonds'
  },
  'risk-veryhigh': {
    color: '#FF0000',
    comment: 'Exclusively for marking fonds'
  },
};

// Initialize the result object
const result = {};

// Iterate over the colorMappings object
for (const [key, { color, comment }] of Object.entries(colorMappings)) {
  // Construct the result using the key, color, and comment
  result[sanitizeValue(key)] = `rgb(var(--sd-color-${sanitizeKey(sanitizeValue(key))}, ${getColor(color)}) / <alpha-value>) /* ${comment} */`;
}
```

Could you try something like this?

2024-02-20 12:58 UTC, mariohamann requested changes
https://github.com/solid-design-system/solid/pull/757/files#r1495779989

This should be definitely changed.

2024-02-23 10:00 UTC, Vahid1919 commented
@saemik94 This seems to have made significant changed to some of the components (sd-teaser-media. sd-video and sd-flag) Is this intended? 

Example: 
![image](https://github.com/solid-design-system/solid/assets/63849626/4e4c79f5-f272-495f-a177-8e94e81c8784)


You can take a look at the chromatic UI tests to look at the specifics

2024-02-26 08:59 UTC, saemik94 commented
@Vahid1919 thanks for the hint! I was able to fix it :)

2024-02-27 08:32 UTC, Vahid1919 approved these changes

2024-02-27 10:56 UTC, karlbaumhauer approved these changes

2024-02-27 14:11 UTC, merged