feat: ✨ sd-footnotes
solid-design-system/solid pull request #958
Opened 2024-04-17 11:49 UTC by mariohamann

## Description:

## Definition of Reviewable:

- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated
- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

2024-04-18 09:39 UTC, yoezlem approved these changes

2024-04-25 12:50 UTC, karlbaumhauer commented
@Vahid1919 pls modify the description of this PR to be marked as Breaking change.

2024-04-25 12:51 UTC, karlbaumhauer requested changes

2024-04-25 12:58 UTC, Vahid1919 commented on packages/components/src/solid-styles.css
>  @import './styles/list/list.css';
@karlbaumhauer We do not have a migration guide for sd-footnote as it was not a part of the UI Component Library.

2024-04-25 12:58 UTC, karlbaumhauer commented on packages/components/src/styles/footnotes/footnotes.stories.ts
> + * Use the class with a `ol` element to display the footnotes as a numbered list.
@Vahid1919 what do you think about switching the "default" here? A footnote list without numbers (ul) doesn't really match the expectations of a footnote list (IMO).
maybe even with only one lingle list item as you always should add numbers if you have more. 

@coraliefeil what do you think? is there even a use case für a footnote list without numbers? 

If so, I would like to see the case specified as best as possible.

2024-04-25 13:45 UTC, karlbaumhauer commented on packages/components/src/solid-styles.css
>  @import './styles/list/list.css';
ups... your right. got mixed up by the libraries... my bad... 🫣

2024-04-26 08:18 UTC, karlbaumhauer approved these changes

2024-04-26 10:31 UTC, merged